# bot.py
import os

import discord
from dotenv import load_dotenv

load_dotenv()
TOKEN = os.getenv('DISCORD_TOKEN')

client = discord.Client()

@client.event
async def on_ready():
    print(f'{client.user.name} has connected to Discord!')

@client.event
async def on_member_join(member):
    await member.create_dm()
    await member.dm_channel.send(f'Hi {member.name}, welcome to 2 Truth Notes Discord server!')
    await member.dm_channel.send("Here are the rules for this discord server")
    await member.dm_channel.send('''
RULES FOR DISCORD SERVER "2 TRUTH NOTES"
  1. Notes and Q&A for notes only. Anything else should be in the channels #off-topic  or #questions  or #general  or #homework-help 
  2. No spamming, spammers will receive a ban for 7 days
  3. All notes should be pinned and only notes should be pinned
  4. You may share this server with ppl if they are in the class with the following shared link:
       https://discord.gg/3d8Fg3PPSf
  5. No inappropriate and unrelated images, stickers, emojis or comments except for the channels #off-topic and #general
  6. Study session planning must be strictly kept to the #study-session-planning  channel.
END OF RULS FOR DISCORD SERVER "2 TRUTH NOTES"
    ''')
    await member.dm_channel.send("Feel free to contact me. I won't reply you.")
    await member.dm_channel.send("Thanks!")
    await member.dm_channel.send("(Autogenerated Message from note-tifier-bot by AzlanCoding)")

client.run(TOKEN)
